const taskInput = document.getElementById("taskInput")
const addNewTask = document.getElementById("addNewTask")
const category = document.getElementById("category")
const status = document.getElementById("status")
// const deadline = document.getElementById("deadline")
const display = document.getElementById("display")